// wasm/ui/App.vue
<script setup lang="ts">
import { ref, computed, reactive, onMounted } from 'vue'

import { EDI } from '../pkg/edinburgh_wasm'

import Ensemble from './components/Ensemble.vue'
import Service from './components/Service.vue'

let edi = new EDI()
let ws: WebSocket | null = null
// let frameBuffer = []

let audioContext: AudioContext
let workletNode: AudioWorkletNode
let decoder: AudioDecoder

const numFramesReceived = ref(0)

const selectedServiceSid = ref(0)
const selectedScid = ref(0)

const scids = ref([])

let ensemble = reactive<{
  eid: number
  label?: string
  short_label?: string
  services: {
    sid: number
    scid?: number
    label?: string
    short_label?: string
  }[]
}>({
  eid: 0,
  services: [],
})

const services = computed(() => {
  const s = ensemble?.services ?? []
  return s
    .filter((s) => s.label !== undefined)
    .map((service) => ({
      ...service,
      isCurrent: service.sid === selectedServiceSid.value,
    }))
    .sort((a, b) => a.label!.localeCompare(b.label!))
})

const service = computed(() => {
  return services.value.find((s) => s.sid === selectedServiceSid.value)
})

const connect = async () => {
  await initializeAudioDecoder()

  if (!ws) {
    ws = new WebSocket("ws://localhost:9000")

    ws.binaryType = "arraybuffer"

    // ws.onmessage = async (event) => {
    //   await edi.feed(new Uint8Array(event.data))
    // };

    ws.onmessage = (event) => {
      edi.feed(new Uint8Array(event.data))
    };

    ws.onclose = () => {
      console.info("WebSocket closed")
      ws = null
    };

    ws.onerror = (e) => {
      console.error("WebSocket error:", e)
    };

  }

  // edi.on_edi_event(async (evt) => {
  //   console.log('EDI EVENT:', evt)
  // })

  edi.on_ensemble_update(async (ensembleData) => {
    console.log('ENSEMBLE:', ensembleData)
    Object.assign(ensemble, ensembleData)
  })

  edi.on_aac_segment(async (aacSegment) => {
    // console.log('AAC SEGMENT:', aacSegment)
    if (!scids.value.includes(aacSegment.scid)) {
      scids.value = [...scids.value, aacSegment.scid]
    }

    if (aacSegment.scid !== selectedScid.value) {
      return
    }
    // console.log('AAC SEGMENT:', aacSegment)

    aacSegment.frames.forEach((frame) => {
      // console.log('AAC FRAME:', frame)
      processAACSegment(new Uint8Array(frame))
    });

    // await processAACSegment(new Uint8Array(aacSegment.data))
  })
}



/*
edi.on_edi_frame(async (frameData) => {
  if (numFramesReceived.value < 1) {
    console.log('EDI FRAME:', frameData)
  }
  numFramesReceived.value++
})

edi.on_ensemble_update(async (ensembleData) => {
  console.log('ENSEMBLE:', ensembleData)
  Object.assign(ensemble, ensembleData)
})

edi.on_aac_segment(async (aacSegment) => {
  if (!scids.value.includes(aacSegment.scid)) {
    scids.value = [...scids.value, aacSegment.scid]
  }

  if (aacSegment.scid !== selectedScid.value) {
    return
  }

  await processAACSegment(new Uint8Array(aacSegment.data))
})
*/


// onMounted(() => {
//   // TODO: fix audio context initialization
//   connect()
// })

const disconnect = async () => {
  if (edi) {
    edi.disconnect()
    edi = null;
  }
  if (decoder) {
    decoder.reset()
  }
  // reset everything
  Object.assign(ensemble, {
    eid: 0,
    services: [],
  })
}

const initializeAudioDecoder = async () => {
  if (decoder) {
    console.info('decoder already initialized')
    return
  }

  audioContext = new AudioContext({
    latencyHint: 'balanced',
    sampleRate: 24000,
  })

  await audioContext.audioWorklet.addModule('pcm-processor.js')

  workletNode = new AudioWorkletNode(audioContext, 'pcm-processor', {
    outputChannelCount: [2],
  })

  workletNode.connect(audioContext.destination)

  decoder = new AudioDecoder({
    output: (audioData) => {
      playDecodedAudio(audioData)
    },
    error: (e) => console.error('Decoder error:', e),
  })

  const asc = new Uint8Array([0x13, 0x14, 0x56, 0xe5, 0x98])

  decoder.configure({
    codec: 'mp4a.40.5',
    sampleRate: 48000,
    numberOfChannels: 2,
    description: asc.buffer,
  })
}

const processAACSegment = async (aacSegment) => {
  const chunk = new EncodedAudioChunk({
    type: 'key',
    timestamp: audioContext.currentTime * 1e6,
    data: aacSegment.buffer,
  })

  decoder.decode(chunk)
}

const playDecodedAudio = async (audioData) => {
  const numChannels = 2
  const numFrames = audioData.numberOfFrames

  const pcmData = [new Float32Array(numFrames), new Float32Array(numFrames)]

  for (let channel = 0; channel < numChannels; channel++) {
    audioData.copyTo(pcmData[channel], { planeIndex: channel })
  }

  workletNode.port.postMessage({
    type: 'audio',
    samples: pcmData,
  })
}

const setScid = async (scid) => {
  selectedScid.value = scid
  console.log('SCID:', scid)

  decoder.reset()

  const asc = new Uint8Array([0x13, 0x14, 0x56, 0xe5, 0x98])

  decoder.configure({
    codec: 'mp4a.40.5',
    sampleRate: 48000,
    numberOfChannels: 2,
    description: asc.buffer,
  })

  workletNode.port.postMessage({
    type: 'reset',
  })
}

const selectService = async (sid: number) => {
  selectedServiceSid.value = sid
  console.log('SID:', sid)

  await setScid(service.value?.scid ?? 0);
}
</script>

<template>
  <main>
    <div>
      <div>
        <button @click="connect">Connect</button>
        <button @click="disconnect">Disconnect</button>
      </div>

      <div>
        <Ensemble :ensemble="ensemble" />
      </div>

      <div>
        <pre v-text="service" />
      </div>


      <div>
        <div>
          <h3>Services</h3>
        </div>
        <Service v-for="service in services" :key="service.scid" :service="service"
          :is-current="service.scid === selectedScid" @select="selectService(service.sid)"
          @play="setScid(service.scid === selectedScid ? 0 : service.scid)" />
      </div>
    </div>
  </main>
</template>

<style scoped>
button {
  margin: 5px;
  padding: 8px 12px;
  cursor: pointer;
}
</style>

// frontend/src/App.svelte
<script>
  let ws;
  let audioContext;
  let workletNode;
  let decoder;

  let isDecoding = $state(false);

  const connect = async () => {
    await initializeAudioDecoder();

    if (!ws) {
      ws = new WebSocket("ws://localhost:9001");

      ws.binaryType = "arraybuffer";

      ws.onmessage = async (event) => {
        await processAACFrame(new Uint8Array(event.data));
      };

      ws.onclose = () => {
        console.info("WebSocket closed");
        ws = null;
      };

      ws.onerror = (e) => {
        console.error("WebSocket error:", e);
      };

    }
    console.debug("ws:", ws);
  };

  const disconnect = async () => {
    if (ws) {
      ws.close();
      ws = null;
    }
  };

  const initializeAudioDecoder = async () => {
    if (decoder) {
      console.info("decoder already initialized");
      return;
    }

    audioContext = new AudioContext({
      latencyHint: "balanced",
      sampleRate: 24000,
    });
    await audioContext.audioWorklet.addModule("pcm-processor.js");

    workletNode = new AudioWorkletNode(audioContext, "pcm-processor", {
      outputChannelCount: [2],
    });
    workletNode.connect(audioContext.destination);

    decoder = new AudioDecoder({
      output: (audioData) => {
        playDecodedAudio(audioData);
      },
      error: (e) => console.error("Decoder error:", e),
    });

    const asc = new Uint8Array([0x13, 0x14, 0x56, 0xe5, 0x98]);

    decoder.configure({
      codec: "mp4a.40.5",
      sampleRate: 48000,
      numberOfChannels: 2,
      description: asc.buffer,
    });

    decoder.ondequeue = (e) => {
      // console.debug("decoder.ondequeue", e);
    };

  };

  const processAACFrame = async (aacFrame) => {
    const chunk = new EncodedAudioChunk({
      type: "key",
      timestamp: audioContext.currentTime * 1e6, // timestamp is needed but has no effect
      data: aacFrame.buffer,
    });

    decoder.decode(chunk);

  };

  const playDecodedAudio = async (audioData) => {
    const numChannels = 2;
    const numFrames = audioData.numberOfFrames;

    let pcmData = [new Float32Array(numFrames), new Float32Array(numFrames)];

    for (let channel = 0; channel < numChannels; channel++) {
      audioData.copyTo(pcmData[channel], { planeIndex: channel });
    }

    workletNode.port.postMessage({
      type: "audio",
      samples: pcmData,
    });

    isDecoding = true;

  };
</script>

<main>
  <div>
    <h1>HE-AAC</h1>
    <button onclick={connect}>Connect</button>
    <button onclick={disconnect}>Disconnect</button>
    <div>
      <p>Decoding: {isDecoding ? "Yes" : "No"}</p>
    </div>
  </div>
</main>
